root:
  controller: Server\Api\Controllers\RootController
  paths:
    - path: /
      method: GET
      action: indexAction
      services:
        - Server\Http\HttpRequest

auth:
  controller: Server\Api\Controllers\AuthController
  paths:
    - path: /register
      method: POST
      action: registerAction
      parameters:
        - nickname
        - email
        - password
      services:
        - Server\Http\HttpRequest
    - path: /login
      method: POST
      action: loginAction
      parameters:
        - email
        - password
      services:
        - Server\Http\HttpRequest
        - Server\Http\JWT
    - path: /myself
      method: GET
      action: myselfAction
      services:
        - Server\Http\HttpRequest
        - Server\Http\JWT

journals:
  controller: Server\Api\Controllers\JournalController
  paths:
    - path: /journals/add
      method: POST
      action: addJournalAction
      parameters:
        - title
        - content
      services:
        - Server\Http\HttpRequest
    - path: /journals
      method: GET
      action: getUserJournals
      services:
        - Server\Http\HttpRequest
    - path: /journal
      method: GET
      action: retrieveJournalAction
      services:
        - Server\Http\HttpRequest
    - path: /journals/edit
      method: PUT
      action: editJournalAction
      parameters:
        - title
        - content
        - date
      services:
        - Server\Http\HttpRequest
    - path: /journals/delete
      method: DELETE
      action: deleteJournalAction
      services:
        - Server\Http\HttpRequest