# Configuration File
#
# The routes configuration files defines all of the mapping
# between the application routes and the controllers of the
# software as well as the HTTP methods the accept and services
# parameters and method to be executed.
#
# TODO: Make this file doc better.

root:
  controller: Server\Api\Controllers\RootController
  paths:
    - path: /
      method: GET
      action: indexAction

auth:
  controller: Server\Api\Controllers\AuthController
  paths:
    - path: /register
      method: POST
      action: registerAction
      parameters:
        - nickname
        - email
        - password
      services:
        - Server\Http\JWT
        - Server\Api\Services\MailingService
    - path: /login
      method: POST
      action: loginAction
      parameters:
        - email
        - password
      services:
        - Server\Http\JWT
    - path: /myself
      method: GET
      action: myselfAction
    - path: /mail-confirmation
      method: GET
      action: confirmEmailAction
      services:
        - Server\Http\JWT
    - path: /resend-mail
      method: GET
      action: resendEmailTokenAction
      services:
        - Server\Http\JWT
        - Server\Api\Services\MailingService

journals:
  controller: Server\Api\Controllers\JournalController
  paths:
    - path: /journals/add
      method: POST
      action: addJournalAction
      parameters:
        - title
        - content
        - share
    - path: /journals
      method: GET
      action: getUserJournals
    - path: /journal
      method: GET
      action: retrieveJournalAction
    - path: /journals/edit
      method: POST
      action: editJournalAction
      parameters:
        - title
        - content
        - date
        - share
    - path: /journals/delete
      method: DELETE
      action: deleteJournalAction
    - path: /journals/shared
      method: GET
      action: showSharedAction